package me.parham1995.notes.ui.icon

import androidx.compose.ui.graphics.vector.addPathNodes
import com.google.common.truth.Truth.assertThat
import org.junit.Test
import java.io.File

class LucideSetTest {
    @Test
    fun `reads a stroke-only icon`() {
        val set = LucideSet.parse("""{"version":"1","icons":{"star":"M1 2L3 4"}}""")

        assertThat(set.sourceOf("star")).isEqualTo("M1 2L3 4" to null)
    }

    @Test
    fun `reads an icon that also has filled geometry`() {
        val set = LucideSet.parse("""{"version":"1","icons":{"tag":["M1 2","M3 4"]}}""")

        assertThat(set.sourceOf("tag")).isEqualTo("M1 2" to "M3 4")
    }

    @Test
    fun `an unknown icon is absent rather than an error`() {
        val set = LucideSet.parse("""{"version":"1","icons":{}}""")

        assertThat(set.sourceOf("nope")).isNull()
        assertThat("nope" in set).isFalse()
    }

    @Test
    fun `a file that is not the expected shape loads as empty`() {
        assertThat(LucideSet.parse("""{"icons":[]}""").size).isEqualTo(0)
        assertThat(LucideSet.parse("""[]""").size).isEqualTo(0)
    }

    /**
     * The asset is generated by `tools/lucide.py`, which converts circles,
     * rects, lines and polygons into path commands and rewrites relative
     * movetos so an icon's sub-paths can be concatenated. All of that is
     * machinery that fails quietly -- a bad conversion produces a string that
     * is still valid JSON and still looks like path data, and only shows up as
     * a glyph drawn in the wrong place.
     *
     * So every icon in the shipped asset is run through the same parser the app
     * draws with. It does not prove the geometry is right, but it does prove
     * the whole set is parseable, which a regenerated asset can silently stop
     * being.
     */
    @Test
    fun `every icon in the shipped asset parses`() {
        val asset = File("src/main/assets/lucide.json")
        assertThat(asset.exists()).isTrue()
        val set = LucideSet.parse(asset.readText())
        assertThat(set.size).isAtLeast(2_000)

        val broken = mutableListOf<String>()
        for (name in set.names) {
            val (stroke, fill) = set.sourceOf(name)!!
            for (data in listOfNotNull(stroke.takeIf { it.isNotEmpty() }, fill)) {
                val nodes = runCatching { addPathNodes(data) }.getOrNull()
                // An unparseable string yields nothing to draw, which is how a
                // broken icon would reach the device looking merely absent.
                if (nodes.isNullOrEmpty()) broken += name
            }
        }
        assertThat(broken).isEmpty()
    }

    /**
     * Concatenation is only safe while no sub-path after the first starts with
     * a relative moveto, and 1,095 of the source icons do. The generator
     * rewrites them; this is the check that it still does.
     */
    @Test
    fun `no icon in the shipped asset starts a path with a relative moveto`() {
        val set = LucideSet.parse(File("src/main/assets/lucide.json").readText())

        val offenders =
            set.names.filter { name ->
                val (stroke, fill) = set.sourceOf(name)!!
                listOfNotNull(stroke.takeIf { it.isNotEmpty() }, fill).any { it.startsWith("m") }
            }

        assertThat(offenders).isEmpty()
    }

    @Test
    fun `the icons the vault's own assignments name are all present`() {
        val set = LucideSet.parse(File("src/main/assets/lucide.json").readText())

        // A spread of shapes rather than the vault's real list, which would
        // put its folder names in a public repository.
        val sample = listOf("folder", "file-text", "piggy-bank", "skull", "building", "venetian-mask", "banknote")

        assertThat(set.names).containsAtLeastElementsIn(sample)
    }
}
